# workflow name
name: Generate release-artifacts

# on events
on:
  # release:
  #   types:
  #       - created
  push:
    branches:
      - master
# workflow tasks
jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.14.2
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: v1.14.2
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: cloudflare_ddns
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
