# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types:
        - created

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, linux/arm, darwin/amd64, darwin/arm windows/amd64'
            package: ''
            name: 'cloudflare_ddns'
            compress: 'true'
            dest: 'dist'
